
import { PosePrompt } from './types';

const POSES_RAW_DATA = [
  // --- EXECUTIVE (EXISTENTES) ---
  { id: 'exec-1', category: 'Executive', title: 'O Pensador Corporativo', poseTechnical: 'Sentado, cotovelo apoiado na mesa, mão fechada sustentando o queixo, olhar focado na câmera.', thumbId: '1560250097-0b93528c311a', wardrobe: 'Terno slim fit azul marinho, camisa branca de colarinho rígido, relógio de luxo.', environment: 'Escritório executivo com luz de fim de tarde entrando por janelas amplas.' },
  { id: 'exec-2', category: 'Executive', title: 'Autoridade Confiante', poseTechnical: 'Em pé, braços cruzados sobre o peito, ombros levemente recuados, postura ereta, sorriso discreto.', thumbId: '1573496359142-b8d87734a5a2', wardrobe: 'Blazer cinza grafite sobre camisa social, postura de liderança.', environment: 'Hall de entrada de mármore com iluminação de teto sofisticada.' },
  { id: 'exec-3', category: 'Executive', title: 'Ajuste de Punho', poseTechnical: 'Em pé, tronco levemente virado de lado, cabeça voltada para a câmera, mãos ajustando a abotoadura do punho esquerdo.', thumbId: '1507679799982-c3389e4467ec', wardrobe: 'Traje formal completo, foco nos detalhes das mãos e acessórios.', environment: 'Estúdio escuro com luz de contorno (rim light) dramática.' },
  { id: 'exec-4', category: 'Executive', title: 'O Visionário Moderno', poseTechnical: 'Sentado de lado em uma cadeira de design, pernas cruzadas, um braço relaxado no encosto, outro segurando um tablet, olhar visionário para o horizonte.', thumbId: '1484133119234-d4df096b22c8', wardrobe: 'Suéter de gola alta preto (turtleneck), óculos de armação fina, calça de alfaiataria.', environment: 'Loft industrial com paredes de concreto exposto e luz suave lateral.' },

  // --- EXECUTIVE (NOVAS +10) ---
  { id: 'exec-5', category: 'Executive', title: 'Power Stance Window', poseTechnical: 'Em pé de costas para uma janela panorâmica, mãos nos bolsos da calça, pernas levemente afastadas, cabeça virada para a câmera.', thumbId: '1556767664157-c1625bb0102f', wardrobe: 'Sobretudo de lã premium sobre terno cinza.', environment: 'Skyscraper office à noite com luzes da cidade ao fundo.' },
  { id: 'exec-6', category: 'Executive', title: 'Boardroom Strategist', poseTechnical: 'Sentado na cabeceira de uma mesa de vidro, braços apoiados sobre a mesa, dedos entrelaçados, postura levemente inclinada para frente.', thumbId: '1491333324055-6627d9b6ec1f', wardrobe: 'Camisa social azul claro, gravata de seda, postura de decisão.', environment: 'Sala de reuniões minimalista com luz natural frontal.' },
  { id: 'exec-7', category: 'Executive', title: 'The Phone Call Deal', poseTechnical: 'Em pé, caminhando levemente, segurando um smartphone próximo ao ouvido com uma mão, a outra mão no bolso, expressão séria e focada.', thumbId: '1519085114933-2a1a2e4b2d3d', wardrobe: 'Blazer casual navy sobre camiseta branca de alta qualidade.', environment: 'Terraço corporativo urbano com vegetação moderna.' },
  { id: 'exec-8', category: 'Executive', title: 'The Signature Look', poseTechnical: 'Sentado, inclinado sobre um documento, caneta tinteiro na mão direita, olhar levantando para a câmera no momento da assinatura.', thumbId: '1551836022-77443109aa39', wardrobe: 'Paletó de veludo escuro, camisa branca.', environment: 'Escritório clássico com móveis de madeira nobre.' },
  { id: 'exec-9', category: 'Executive', title: 'Architect of Success', poseTechnical: 'Debruçado sobre uma mesa com plantas arquitetônicas, mãos espalmadas na mesa, olhar determinado para os planos.', thumbId: '1503387873418-8f830323b37b', wardrobe: 'Camisa de botões com mangas dobradas, relógio cronógrafo.', environment: 'Ateliê de arquitetura com luz zenital (teto).' },
  { id: 'exec-10', category: 'Executive', title: 'The Keynote Speaker', poseTechnical: 'Em pé, um braço estendido com a palma para cima em gesto de explicação, olhar carismático para um público imaginário.', thumbId: '1475721027475-29fb08ffbb71', wardrobe: 'Terno completo de três peças, lapela impecável.', environment: 'Palco moderno com iluminação de spot e fundo escuro.' },
  { id: 'exec-11', category: 'Executive', title: 'Tech Founder Lean', poseTechnical: 'Sentado na borda de uma mesa, uma perna balançando, mãos apoiadas na borda da mesa, visual informal e inovador.', thumbId: '1507679613915-c8e907ff993b', wardrobe: 'Camiseta premium preta, calça chino escura.', environment: 'Hub de inovação com luzes LED RGB sutis ao fundo.' },
  { id: 'exec-12', category: 'Executive', title: 'Global News Profile', poseTechnical: 'Sentado em ângulo de 45 graus, pernas cruzadas, costas retas, olhar intelectual e direto.', thumbId: '1522202225-3168a1438d94', wardrobe: 'Cardigan de luxo sobre camisa social.', environment: 'Set de entrevista de TV com luzes de produção visíveis.' },
  { id: 'exec-13', category: 'Executive', title: 'The Mentor Handshake', poseTechnical: 'Corpo frontal, uma mão estendida para um aperto de mão, a outra mão no quadril, sorriso receptivo.', thumbId: '1542744094-246abc413527', wardrobe: 'Blazer bege, camisa de linho.', environment: 'Área de lounge de hotel de luxo.' },
  { id: 'exec-14', category: 'Executive', title: 'The Briefcase Walk', poseTechnical: 'Em pé, de perfil, segurando uma pasta de couro executiva, passo largo simulando caminhada, olhar focado à frente.', thumbId: '1573164574514-49a5530188b6', wardrobe: 'Sobretudo longo, calça social slim.', environment: 'Distrito financeiro com luz de "Blue Hour".' },

  // --- FASHION (EXISTENTES) ---
  { id: 'fash-1', category: 'Fashion', title: 'Editorial High-Angle', poseTechnical: 'Sentado no chão, pernas dobradas assimetricamente, um braço apoiado no joelho, cabeça inclinada.', thumbId: '1534528741775-53994a69daeb', wardrobe: 'Roupa conceitual oversized, tecidos com textura rica, botas de couro.', environment: 'Estúdio minimalista cinza, luz Butterfly suave.' },
  { id: 'fash-2', category: 'Fashion', title: 'Perfil Dinâmico', poseTechnical: 'Em pé, perfil total para a câmera, corpo inclinado para frente, mão no bolso traseiro, olhar por cima do ombro.', thumbId: '1529139513477-3235a739174b', wardrobe: 'Jaqueta de couro premium, calça de alfaiataria preta.', environment: 'Cenário urbano industrial com luz neon lateral.' },
  { id: 'fash-3', category: 'Fashion', title: 'Vogue Squat', poseTechnical: 'Agachado de forma simétrica, braços apoiados nos joelhos, mãos caídas relaxadas, olhar intenso e fixo na lente.', thumbId: '1509633042648-8f151bbad7c1', wardrobe: 'Look monocromático high-fashion, acessórios metálicos grandes.', environment: 'Fundo infinito branco puro com sombras duras e estilizadas.' },

  // --- FASHION (NOVAS +10) ---
  { id: 'fash-4', category: 'Fashion', title: 'The S-Curve Lean', poseTechnical: 'Em pé, peso do corpo na perna direita, quadril projetado, braços em ângulos geométricos, tronco inclinado criando uma curva em S.', thumbId: '1515886657662-85880483ba52', wardrobe: 'Vestido escultural ou terno de corte assimétrico.', environment: 'Galeria de arte branca com luz focal.' },
  { id: 'fash-5', category: 'Fashion', title: 'Avant-Garde Floor', poseTechnical: 'Deitado de lado no chão, um braço estendido para cima, pernas cruzadas de forma artística, olhar etéreo.', thumbId: '1481327835137-b226f188310e', wardrobe: 'Tecidos fluidos, seda, cores vibrantes.', environment: 'Estúdio escuro com uma única luz de feixe estreito.' },
  { id: 'fash-6', category: 'Fashion', title: 'The Wind Flow', poseTechnical: 'Em pé, braços abertos, corpo levemente inclinado para trás, efeito de vento forte no cabelo e roupas.', thumbId: '1506667527668-da8dd169d217', wardrobe: 'Capa longa ou vestido esvoaçante.', environment: 'Deserto ao pôr do sol com luz dourada dramática.' },
  { id: 'fash-7', category: 'Fashion', title: 'Geometric Chair', poseTechnical: 'Sentado de forma não convencional em uma cadeira de metal, pernas elevadas, braços entrelaçados nas pernas.', thumbId: '1525875975047-cfb7dec6943f', wardrobe: 'Moda futurista, materiais reflexivos.', environment: 'Cenário cinza high-key.' },
  { id: 'fash-8', category: 'Fashion', title: 'The Muse Mirror', poseTechnical: 'Sentado de frente para um espelho grande, capturando o reflexo e o perfil real simultaneamente.', thumbId: '1494791363641-7667c9f5263a', wardrobe: 'Joias de alta costura, maquiagem editorial.', environment: 'Camarim de luxo com luzes de lâmpada clássicas.' },
  { id: 'fash-9', category: 'Fashion', title: 'Cyber Noir Edge', poseTechnical: 'Em pé, capuz levantado, metade do rosto na sombra, postura defensiva mas elegante.', thumbId: '1531747118-d42f4c054211', wardrobe: 'Techwear preto, jaqueta com brilho sintético.', environment: 'Beco chuvoso com reflexos de neon azul e rosa.' },
  { id: 'fash-10', category: 'Fashion', title: 'The High-Neck Turn', poseTechnical: 'De costas para a câmera, virando apenas o pescoço e olhar para trás com expressão de mistério.', thumbId: '1503341456326-da2863ad1b4c', wardrobe: 'Gola alta preta, brincos de diamante.', environment: 'Fundo preto profundo (Vantablack style).' },
  { id: 'fash-11', category: 'Fashion', title: 'Retro Hollywood Glam', poseTechnical: 'Deitado em um divã, mão segurando um porta-cigarro longo (adereço), pernas elegantemente posicionadas.', thumbId: '1485462537747-04856f6d903f', wardrobe: 'Vestido de gala com brilhos, estola de pele sintética.', environment: 'Mansão vintage anos 50.' },
  { id: 'fash-12', category: 'Fashion', title: 'The Street Elite Squat', poseTechnical: 'Agachado em um ambiente urbano, uma mão no chão, outra no joelho, olhar desafiador.', thumbId: '1520333781020-2c351577f49a', wardrobe: 'Tênis de edição limitada, jaqueta puffer.', environment: 'Escadaria de museu moderno.' },
  { id: 'fash-13', category: 'Fashion', title: 'The Abstract Shadow', poseTechnical: 'Em pé contra uma parede, luz projetando sombras de persiana sobre o rosto e corpo, postura estática.', thumbId: '1490480681583-ff7688a2c35b', wardrobe: 'Roupas com recortes geométricos.', environment: 'Quarto minimalista com luz de sol forte de janela.' },

  // --- CASUAL (EXISTENTES) ---
  { id: 'cas-1', category: 'Casual', title: 'Relaxed Coffee Break', poseTechnical: 'Sentado em banqueta alta, mãos segurando uma xícara de café próxima ao rosto, corpo relaxado e inclinado.', thumbId: '1517832207056-42724122463d', wardrobe: 'Suéter de cashmere beige, calça jeans premium.', environment: 'Cafeteria moderna com profundidade de campo rasa (bokeh).' },
  { id: 'cas-2', category: 'Casual', title: 'Leaning Natural', poseTechnical: 'Apoiado com as costas em uma parede, uma perna dobrada com o pé na parede, mãos nos bolsos da frente.', thumbId: '1488161628892-d0f94080126a', wardrobe: 'Camiseta de algodão pima branca, jaqueta bomber aberta.', environment: 'Parede de tijolos aparentes, iluminação natural suave.' },

  // --- CASUAL (NOVAS +10) ---
  { id: 'cas-3', category: 'Casual', title: 'The Library Reader', poseTechnical: 'Sentado no chão de uma biblioteca, encostado em estante de livros, lendo um livro aberto no colo.', thumbId: '1519337028930-de470ac82083', wardrobe: 'Cardigan de lã grossa, óculos de grau.', environment: 'Biblioteca aconchegante com luz quente.' },
  { id: 'cas-4', category: 'Casual', title: 'Backyard Zen', poseTechnical: 'Sentado de pernas cruzadas na grama, mãos relaxadas nos joelhos, olhos fechados, rosto voltado para o sol.', thumbId: '1506126613408-ca43627526bb', wardrobe: 'Camisa de linho, calça leve.', environment: 'Jardim ensolarado com flores ao fundo.' },
  { id: 'cas-5', category: 'Casual', title: 'The Urban Wanderer', poseTechnical: 'Caminhando em uma faixa de pedestres, olhando para o lado como se estivesse distraído, fones de ouvido no pescoço.', thumbId: '1488161628892-d0f94080126a', wardrobe: 'Jaqueta jeans, mochila estilosa.', environment: 'Cruzamento movimentado de cidade grande.' },
  { id: 'cas-6', category: 'Casual', title: 'Sunset Balcony Lean', poseTechnical: 'Apoiado com os cotovelos em um parapeito de varanda, olhando para o horizonte, segurando uma taça.', thumbId: '1507246196591-dda82f354930', wardrobe: 'Polo branca, bermuda de alfaiataria.', environment: 'Varanda com vista para o mar no pôr do sol.' },
  { id: 'cas-7', category: 'Casual', title: 'The Creative Mess', poseTechnical: 'Sentado em uma mesa de ateliê rodeado de tintas, mão suja de tinta no rosto, olhar cansado e satisfeito.', thumbId: '1513360309081-066188874ed9', wardrobe: 'Camiseta velha com manchas de tinta, avental de couro.', environment: 'Estúdio de artista com muita luz natural.' },
  { id: 'cas-8', category: 'Casual', title: 'Rainy Day Mood', poseTechnical: 'Sentado em uma poltrona próxima à janela, olhando o reflexo da chuva no vidro, abraçando os próprios joelhos.', thumbId: '1515023110731-78b05c6114f0', wardrobe: 'Moletom oversized, meias de lã.', environment: 'Interior de casa de campo em dia de chuva.' },
  { id: 'cas-9', category: 'Casual', title: 'The Record Store Dig', poseTechnical: 'Agachado folheando discos de vinil em uma loja, fones de ouvido grandes, olhar de descoberta.', thumbId: '1498138404777-fd3e43a4b291', wardrobe: 'Camiseta de banda vintage, calça cargo.', environment: 'Loja de discos retrô com luzes quentes.' },
  { id: 'cas-10', category: 'Casual', title: 'Pet Bond Moment', poseTechnical: 'Sentado no chão abraçando um cachorro grande (labrador), rosto colado no do pet, sorriso genuíno.', thumbId: '1537151158117-06399434b7f8', wardrobe: 'Suéter de tricot, jeans azul claro.', environment: 'Parque arborizado com luz filtrada pelas árvores.' },
  { id: 'cas-11', category: 'Casual', title: 'The Road Trip Stop', poseTechnical: 'Sentado no capô de um carro clássico estacionado no acostamento, olhando o mapa físico, cabelo ao vento.', thumbId: '1469813008292-24376043498b', wardrobe: 'Camisa xadrez aberta, bota de trilha.', environment: 'Estrada deserta com montanhas ao fundo.' },
  { id: 'cas-12', category: 'Casual', title: 'Kitchen Chef Candid', poseTechnical: 'Em pé na cozinha, picando vegetais, rindo para alguém fora de quadro, luz de janela lateral.', thumbId: '1556910103-0c1945c44773', wardrobe: 'Camisa social branca com mangas dobradas.', environment: 'Kozinha moderna e minimalista.' },

  // --- ACTION (EXISTENTES) ---
  { id: 'act-1', category: 'Action', title: 'Sprint de Estúdio', poseTechnical: 'Corpo em movimento de corrida capturado em freeze-frame, braços em ângulo dinâmico, expressão de esforço.', thumbId: '1517836357463-d25dfeac3438', wardrobe: 'Performance gear de compressão tecnológica, tênis de corrida de elite.', environment: 'Ginásio high-tech com fumaça atmosférica e luzes azuis.' },

  // --- ACTION (NOVAS +10) ---
  { id: 'act-2', category: 'Action', title: 'The Yoga Crow', poseTechnical: 'Equilibrado nas mãos na posição de corvo (Bakasana), pés fora do chão, olhar focado à frente.', thumbId: '1506126613408-ca43627526bb', wardrobe: 'Roupas de yoga premium pretas.', environment: 'Estúdio de yoga com painéis de madeira.' },
  { id: 'act-3', category: 'Action', title: 'The Boxing Hook', poseTechnical: 'Posição de luta, braço direito desferindo um gancho, tronco rotacionado, expressão de força extrema.', thumbId: '1549476464-56e676a160bf', wardrobe: 'Luvas de boxe profissionais, bandagens nos pulsos.', environment: 'Ringue de boxe escuro sob holofote.' },
  { id: 'act-4', category: 'Action', title: 'The Dance Leap', poseTechnical: 'Salto no ar com pernas abertas em Grand Jeté, braços elegantes, flutuando no quadro.', thumbId: '1508700115892-45e01ae29b4a', wardrobe: 'Malha de dança ou roupas leves que mostram movimento.', environment: 'Palco de teatro com luz de fundo intensa.' },
  { id: 'act-5', category: 'Action', title: 'Skate Kickflip Freeze', poseTechnical: 'Suspenso no ar sobre um skate, pés em posição de manobra, braços para equilíbrio, olhar no skate.', thumbId: '1520152371221-3a04e921435e', wardrobe: 'Streetwear, boné, proteção de pulso.', environment: 'Skatepark de concreto sob luz do dia.' },
  { id: 'act-6', category: 'Action', title: 'Tennis Ace Serve', poseTechnical: 'Braço estendido no ponto mais alto do saque, raquete em movimento circular, corpo totalmente esticado.', thumbId: '1592709823052-482a52735846', wardrobe: 'Roupa de tênis branca clássica.', environment: 'Quadra de tênis de saibro.' },
  { id: 'act-7', category: 'Action', title: 'The Martial Arts Kick', poseTechnical: 'Chute lateral alto (Yoko Geri), perna de apoio firme, braços em guarda, equilíbrio perfeito.', thumbId: '1555597673-9736c730afad', wardrobe: 'Kimono branco tradicional (Gi).', environment: 'Dojo tradicional com tatame.' },
  { id: 'act-8', category: 'Action', title: 'Rockstar Solo', poseTechnical: 'Segurando uma guitarra elétrica, pernas afastadas, cabeça jogada para trás, uma mão no braço da guitarra, outra no meio do movimento de dedilhar.', thumbId: '1511739001995-d8355c346852', wardrobe: 'Jaqueta de couro com tachas, jeans rasgado.', environment: 'Palco de show com fumaça e luzes coloridas.' },
  { id: 'act-9', category: 'Action', title: 'The Weightlifter Peak', poseTechnical: 'Segurando barra com pesos acima da cabeça (Snatch), braços travados, expressão de superação, pó de magnésio no ar.', thumbId: '1517836357463-d25dfeac3438', wardrobe: 'Cinturão de força, regata de treino.', environment: 'Academia de Crossfit industrial.' },
  { id: 'act-10', category: 'Action', title: 'The Parkour Vault', poseTechnical: 'Uma mão apoiada em um muro, corpo passando por cima do obstáculo de lado, movimento dinâmico.', thumbId: '1508700115892-45e01ae29b4a', wardrobe: 'Calça jogger, camiseta dry-fit.', environment: 'Arquitetura urbana brutalista.' },
  { id: 'act-11', category: 'Action', title: 'The Surfer Stance', poseTechnical: 'Agachado sobre prancha de surf, braços abertos para equilíbrio, simulando o interior de uma onda.', thumbId: '1502680393847-f196601046ec', wardrobe: 'Wetsuit preto, pele molhada.', environment: 'Estúdio com fundo de projeção oceânica.' },

  // --- DUO (EXISTENTES) ---
  { id: 'duo-1', category: 'Duo', title: 'Power Couple Back-to-Back', poseTechnical: 'Duas pessoas em pé, costas com costas, braços cruzados, cabeças levemente viradas para a câmera.', thumbId: '1531746020798-e795c5394c44', wardrobe: 'Trajes coordenados em tons neutros, estilo editorial.', environment: 'Fundo infinito cinza médio, iluminação de três pontos clássica.', isDuo: true },
  { id: 'duo-2', category: 'Duo', title: 'The Hollywood Gala', poseTechnical: 'Pessoa A com braço em volta da cintura da Pessoa B. Pessoa B com a mão apoiada no ombro da Pessoa A. Ambos inclinados levemente um para o outro, olhando para a câmera com sorrisos de tapete vermelho.', thumbId: '1583939003579-730e3918a45a', wardrobe: 'Trajes de gala: Vestido de seda longo e Smoking sob medida.', environment: 'Entrada de evento luxuoso com flashes de luz ao fundo e carpete vermelho.', isDuo: true },
  { id: 'duo-3', category: 'Duo', title: 'Dynasty Power Sit', poseTechnical: 'Pessoa A sentada em uma poltrona de couro clássica (Chesterfield). Pessoa B em pé logo atrás, com uma mão apoiada no encosto da poltrona e a outra no ombro da Pessoa A. Composição piramidal clássica.', thumbId: '1511895426773-4590651139e4', wardrobe: 'Roupas de grife em tons de terra e preto, joias discretas mas caras.', environment: 'Biblioteca clássica com estantes de livros em madeira escura e luz de abajur quente.', isDuo: true },
  { id: 'duo-4', category: 'Duo', title: 'Minimalist Intimacy', poseTechnical: 'Ambos sentados de frente um para o outro em bancos simples, testas quase se tocando, olhos fechados, mãos entrelaçadas no centro. Captura de perfil lateral.', thumbId: '1516585424504-d2e81c3d7f9d', wardrobe: 'Camisas de linho brancas, visual clean e orgânico.', environment: 'Estúdio zen inundado de luz natural suave, sombras tênues.', isDuo: true },
  { id: 'duo-5', category: 'Duo', title: 'The Street Style Icons', poseTechnical: 'Caminhando em direção à câmera, braços dados, rindo espontaneamente. Passo coordenado. Pessoa A segurando uma bolsa de grife, Pessoa B com a mão no bolso.', thumbId: '1520906580237-446097eea11b', wardrobe: 'Streetwear de luxo, camadas de roupas (layering), óculos escuros premium.', environment: 'Rua de Nova York (SoHo) com profundidade de campo cinematográfica.', isDuo: true },

  // --- DUO (NOVAS +10) ---
  { id: 'duo-6', category: 'Duo', title: 'The Protector Hug', poseTechnical: 'Pessoa A em pé atrás da Pessoa B, envolvendo-a com um abraço protetor pelo tórax. Pessoa B segurando as mãos da Pessoa A. Ambos olhando para a câmera de forma serena.', thumbId: '1520906580237-446097eea11b', wardrobe: 'Casacos de lã coordenados, cachecóis finos.', environment: 'Floresta de pinheiros com névoa suave.', isDuo: true },
  { id: 'duo-7', category: 'Duo', title: 'The Secret Whisper', poseTechnical: 'Pessoa A sussurrando algo no ouvido da Pessoa B, que sorri de forma espontânea. Pessoa A com a mão cobrindo a lateral do rosto.', thumbId: '1516585424504-d2e81c3d7f9d', wardrobe: 'Roupas casuais de alta qualidade, tons pastéis.', environment: 'Lounge de café luxuoso.', isDuo: true },
  { id: 'duo-8', category: 'Duo', title: 'Editorial Separation', poseTechnical: 'Pessoa A em pé em primeiro plano, braços cruzados. Pessoa B sentada ao fundo em um degrau, desfocada levemente (profundidade de campo), ambos olhando para a lente.', thumbId: '1531746020798-e795c5394c44', wardrobe: 'Estilo high-fashion arquitetônico.', environment: 'Fachada de museu de concreto moderno.', isDuo: true },
  { id: 'duo-9', category: 'Duo', title: 'The Dynamic Dance', poseTechnical: 'Pessoa A conduzindo a Pessoa B em um movimento de dança, Pessoa B inclinada para trás com uma perna elevada, mãos dadas no ar.', thumbId: '1508700115892-45e01ae29b4a', wardrobe: 'Roupas de festa elegantes que permitem movimento.', environment: 'Salão de baile iluminado por candelabros.', isDuo: true },
  { id: 'duo-10', category: 'Duo', title: 'The Symmetry Mirror', poseTechnical: 'Ambos de perfil, um de frente para o outro, braços estendidos tocando as pontas dos dedos, criando uma simetria perfeita.', thumbId: '1511895426773-4590651139e4', wardrobe: 'Looks pretos idênticos (turtleneck).', environment: 'Fundo branco infinito com sombras duras.', isDuo: true },
  { id: 'duo-11', category: 'Duo', title: 'The Voyage Couple', poseTechnical: 'Em pé ao lado de malas de couro luxuosas, Pessoa A sentada na mala, Pessoa B em pé ao lado com a mão no ombro, olhando para o horizonte.', thumbId: '1469813008292-24376043498b', wardrobe: 'Trajes de viagem clássicos, chapéus, trench coats.', environment: 'Estação de trem vintage.', isDuo: true },
  { id: 'duo-12', category: 'Duo', title: 'Rooftop Romance', poseTechnical: 'Sentados na beirada de um rooftop, pernas balançando para fora, cabeças encostadas uma na outra, olhando a cidade abaixo.', thumbId: '1507246196591-dda82f354930', wardrobe: 'Visual urbano noturno, jaquetas leves.', environment: 'Topo de prédio com luzes da cidade em bokeh.', isDuo: true },
  { id: 'duo-13', category: 'Duo', title: 'Artistic Contrast', poseTechnical: 'Pessoa A sentada no chão abraçando os joelhos. Pessoa B em pé logo acima, olhando para baixo com a mão no queixo.', thumbId: '1534528741775-53994a69daeb', wardrobe: 'Roupas com texturas contrastantes (couro vs seda).', environment: 'Estúdio industrial com luz lateral forte.', isDuo: true },
  { id: 'duo-14', category: 'Duo', title: 'The Classic Portrait', poseTechnical: 'Enquadramento fechado (close-up) de ambos os rostos lado a lado, ombro com ombro, olhando diretamente para a lente com seriedade.', thumbId: '1583939003579-730e3918a45a', wardrobe: 'Golas altas escuras, foco total na face.', environment: 'Estúdio profissional com iluminação de retrato clássica (Rembrandt).', isDuo: true },
  { id: 'duo-15', category: 'Duo', title: 'The Laughter Break', poseTechnical: 'Ambos sentados em uma mesa de jantar, rindo intensamente com as mãos na mesa, copos de vinho à frente, visual espontâneo.', thumbId: '1556910103-0c1945c44773', wardrobe: 'Roupas de jantar casuais-chiques.', environment: 'Restaurante sofisticado com luz de velas.', isDuo: true }
];

export const POSE_PROMPTS: PosePrompt[] = POSES_RAW_DATA.map(data => ({
  id: data.id,
  title: data.title,
  category: data.category,
  description: `${data.category} Profissional em ambiente de ${data.environment.split(' ')[0]}.`,
  poseTechnical: data.poseTechnical,
  thumbnail: `https://images.unsplash.com/photo-${data.thumbId}?w=800&auto=format&fit=crop&q=90`,
  prompt: `
    POSE CORPORAL OBRIGATÓRIA: ${data.poseTechnical}
    CENÁRIO: ${data.environment}
    VESTUÁRIO: ${data.wardrobe}
    QUALIDADE: Fotografia Publicitária 8K, RAW, Lente 85mm f/1.4, Iluminação de Estúdio Profissional, Chiaroscuro Style, Phase One XF Sensor.
    
    PROTOCOLO DE TRANSFERÊNCIA:
    1. Extraia o ROSTO e IDENTIDADE da imagem de referência.
    2. Aplique esta identidade no corpo que executa a POSE CORPORAL OBRIGATÓRIA descrita acima.
    3. Mantenha ACESSÓRIOS (Óculos, Joias, Adereços de Cabeça) da foto original.
    4. O resultado deve parecer uma sessão de fotos de agência de celebridades onde os modelos foram dirigidos para fazer exatamente esta pose.
  `.trim(),
  isDuo: data.isDuo || false
}));
